### ISSUE TITLE
Request for Apple Silicon Support

### ISSUE THREAD

**Issue by Crear12** [valgur/velodyne_decoder#10]
Hi valgur,
Thank you for providing such an amazing tool. I moved my work flow from an intel MacBook Pro to the Silicon environment, the installation cannot work, tried both ```pip install velodyne-decoder``` (cannot install) and ```pip install git+https://github.com/valgur/velodyne_decoder.git``` (says installed successfully, but the ```vd.Config(model="Alpha Prime", rpm=600)``` cannot be created.
```
Error Message:
    config = vd.Config(model="Alpha Prime", rpm=600)
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. velodyne_decoder.velodyne_decoder_pylib.Config(*, model: Optional[velodyne_decoder::ModelId] = None, calibration: Optional[velodyne_decoder::Calibration] = None, single_return_mode_info: bool = False, min_range: float = 0.1, max_range: float = 200, min_angle: float = 0, max_angle: float = 360, cut_angle: Optional[float] = None, timestamp_first_packet: bool = False, use_device_time: bool = False)

Invoked with: kwargs: model='Alpha Prime', rpm=600
```
Thanks again,
Crear

**Comment by valgur** [comment]
Hi!

I recently switched the default branch to `develop` on the repo. One of the changes there is that the `model` and `rpm` params are detected automatically from the packets, so the params are pretty much unnecessary now.

You can either continue using the master branch with `pip install git+https://github.com/valgur/velodyne_decoder.git@master` or drop the `model` and `rpm` params from the config (or the config param itself altogether).

Regarding Apple Silicon, starting from the next 3.0.0 release, velodyne_decoder will definitely include Apple Silicon and other ARM architectures for the PyPI wheels as well.
