### ISSUE TITLE
Inconsistent frame sizes

### ISSUE THREAD

**Issue by scottike** [valgur/velodyne_decoder#11]
When processing a VLP-16 .PCAP file, the output frames are inconsistent in size. One frame will contain ~32,000 points and the next ~8,000 points. There is a consistent pattern of large, then small frames.

Using VeloView on the same data file, and exporting .CSV files produce frames of ~19,000 points in all frames.

**Comment by valgur** [comment]
Hmm, thanks for mentioning this.
1. Which version or branch of velodyne_decoder are you using?
2. Can you share a snippet of a relevant .pcap file?

**Comment by scottike** [comment]
Well, it was still on 2.3.0, so my mistake. 3.0.0 appears to provide consistent frame size output. I was processing data that included dual returns, so perhaps that was the issue.
