### ISSUE TITLE
Feature Request: Reading Raw Azimuth Angle, Laser ID, Distance, and Timestamp

### ISSUE THREAD

**Issue by Crear12** [valgur/velodyne_decoder#13]
Hi Martin,
Recently we see increasing research with brilliant ideas of using the raw spherical coordinate system data without translating to the cartesian coordinate system. I'm wondering if it's possible to allow passing a parameter to the ```vd.read_pcap``` function like: ```vd.read_pcap(pcap_file_name, config, spherical_coordinate_system=True) ``` to directly return the spherical coordinates like azimuth angle, laser Id, distance? This would save us tons of efforts in reproducing the methodologies proposed in those papers.

Thanks in advance,
Crear

**Comment by valgur** [comment]
Sorry, the effort and added complexity would not be worth the very minor gains in efficiency and convenience provided by such a feature. It's trivial to transform the decoded points into a spherical coordinate system after decoding.
