### ISSUE TITLE
decoded data arrangement

### ISSUE THREAD

**Issue by M-Bahy** [valgur/velodyne_decoder#14]
I used the snippet you provided for Decoding Velodyne data from a PCAP file , however the data comes out as
Y , negative X , Z  
instead of x,y,z . I compared it to veloview extracted csv and it indeed came out as
Points_m_XYZ:1,-Points_m_XYZ:0,Points_m_XYZ:2

I know I can just multiply by -1 and rearrange , but am I doing something wrong ?

Sensor type : VLP-16

**Comment by valgur** [comment]
Oh, right. velodyne_decoder transforms the point cloud to follow ROS conventions for the axes ordering:
* x - forward
* y - left
* z - up

That's definitely something that should be documented better. Thank you for mentioning this!

**Comment by valgur** [comment]
Updated the readme. Thanks again!
