### ISSUE TITLE
Inconsistent decoder output between Numpy versions 1 and 2

### ISSUE THREAD

**Issue by christian-nils** [valgur/velodyne_decoder#19]
Hi,

When using the version 2 of numpy, the output of `velodyne_decoder.ScanDecoder().decode` is not consistent with the output of numpy version 1. 

When running `print_velodyne_packets.py` in the attached zip file (I am using the bag file from https://github.com/valgur/velodyne_decoder/issues/16), you can reproduce the issue. You need to create two virtual environments, one for numpy v1 and the other for numpy v2.

[numpy_v1_vs_v2.zip](https://github.com/user-attachments/files/17750666/numpy_v1_vs_v2.zip)

This is the type of print I get when using v2:
```
[(-7.0058007 , 1.44407053e+01, -2.8227181e+00, 1.0000e+00, -0.07022647,     2,   0,  1)
 (-0.07022647, 2.35098926e-38,  1.1180001e+12, 3.0782e-41, -6.9860806 , 30383, 104, 65)
 (-6.9860806 , 1.45289755e+01, -2.8352208e+00, 1.0000e+00, -0.07017117,     3,   0,  1)
 ...
 (-0.03936471, 2.51644954e-38, -7.5699681e-01, 5.0000e+00,  3.0647848 , 62442, 123, 62)
 ( 3.0647848 , 2.46047646e-01, -3.9017126e-01, 7.0000e+00, -0.03936241,   560,   2,  1)
 (-0.03936241, 2.38787985e-38,  6.1868995e-01, 6.0000e+00,  3.9605806 , 28993, 162, 62)]
```

While I get the following with v1:
```
[(-7.0058007, 14.440705 , -2.8227181,  1., -0.07022647,    2, 0, 1)
 (-6.9860806, 14.5289755, -2.8352208,  1., -0.07017117,    3, 0, 1)
 (-6.954817 , 14.587616 , -2.8421667,  1., -0.07011587,    4, 0, 1) ...
 (-6.008182 , -6.68918  , -1.5780078, 62., -0.00143852, 1246, 0, 1)
 (-6.0235662, -6.659404 , -1.575924 , 64., -0.00138322, 1247, 0, 1)
 (-6.0270514, -6.619004 , -1.571062 , 64., -0.00132799, 1248, 0, 1)]
```

I am not sure where the issue is really located. I hope that could help someone to debug the issue.

Thanks

**Comment by valgur** [comment]
Thanks a lot for reporting this! I have not tested the library at all with NumPy v2 yet.
I'll see if I can find a fix for this over the weekend, perhaps.

**Comment by valgur** [comment]
The Python bindings simply needed to be re-built with NumPy 2.x for compatibility with both 1.x and 2.x. I created a new minor release for this. Thanks again for reporting!

**Comment by christian-nils** [comment]
Thanks for the fix! Have a great day.
