### ISSUE TITLE
v3.0.0 release

### ISSUE THREAD

**Issue by valgur** [valgur/velodyne_decoder#8]
With the significantly simpler configuration, dual-return mode support, reworked scan batching and full precise-timing support for all model versions, I am using this opportunity to create a backwards-incompatible v3.0.0 release soon.

These changes reside in the [`develop`](https://github.com/valgur/velodyne_decoder/tree/develop) branch in the mean time.

Some ideas and loose ends I would still like to implement before the release:
- [x]  autodetection of HDL-64E from input file in Python
- [x]  gps_time→use_device_time
- [x]  Move `__init__.py` contents into separate Python files.
- [x]  StreamDecoder →ScanBatcher
- [x] Return both arrival and device timestamps for scans, drop use_device_time param
- [x]  Always use packet stamp for within-scan timestamps
- [x] Add getters for model ID and return mode to PacketDecoder
- [x] https://github.com/ros-drivers/velodyne/pull/518
- [x] Make `return_type` a separate field
- [x] Add `column` field
- [ ] Fix `__version__` info
- [ ]  Unit tests for PCAP decoding by model
- [ ]  PCAP → rosbag conversion
- [ ]  Support for `rosbags` library input (#6)
- [ ]  Support for re-batching of ROS VelodyneScan packets.
- [ ]  HDL-64E calib extraction from rosbag
- [ ]  HDL-64E autodetection for rosbag
- [ ]  Decode by ROS topic
- [ ]  TelemetryPacket output support for PCAP
- [ ]  VLS-128 timings validation
- [ ]  Update README
- [ ]  Update ChangeLog
- [ ]  Sphinx documentation

**Comment by sjiang95** [comment]
Thanks for your work @valgur. 

When I tried to use the `develop` branch. 

```python
config = vd.Config(model='VLP16') # also tried 'VLP-16'
```

Throws a TypeError

```bash
__init__(): incompatible constructor arguments. The following argument types are supported:
    1. velodyne_decoder_pylib.Config(*, model: Optional[velodyne_decoder::ModelId] = None, calibration: Optional[velodyne_decoder::Calibration] = None, min_range: float = 0.1, max_range: float = 200, min_angle: float = 0, max_angle: float = 360, timestamp_first_packet: bool = False, gps_time: bool = False)

Invoked with: kwargs: model='VLP16'
  File "filename is manually masked", line 12, in <module>
    config = vd.Config(model='VLP16')
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. velodyne_decoder_pylib.Config(*, model: Optional[velodyne_decoder::ModelId] = None, calibration: Optional[velodyne_decoder::Calibration] = None, min_range: float = 0.1, max_range: float = 200, min_angle: float = 0, max_angle: float = 360, timestamp_first_packet: bool = False, gps_time: bool = False)

Invoked with: kwargs: model='VLP16'
```

May I ask how to solve this?

**Comment by valgur** [comment]
The model ID is determined automatically from data in the new version, so you should simply leave out the `model` parameter or leave out the config object altogether when using `read_pcap()` or `read_bag()`. But if you still need to set the model ID for some reason, then the new format is `config = vd.Config(model=vd.Model.VLP16)`.

**Comment by scottike** [comment]
Is the 3.0 version the first to offer dual-return support?

**Comment by valgur** [comment]
> Is the 3.0 version the first to offer dual-return support?

It is, indeed.
