### ISSUE TITLE
error on import in develop branch

### ISSUE THREAD

**Issue by sparshtelus** [valgur/velodyne_decoder#9]
After installing the package from develop branch, I am getting the following error on import.

<img width="776" alt="image" src="https://user-images.githubusercontent.com/112055441/233098339-00d24e40-e53d-492f-9655-5c44390b83e9.png">

`---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-10-2f4cba1e637a> in <module>
----> 1 import velodyne_decoder as vd

/opt/conda/lib/python3.8/site-packages/velodyne_decoder/__init__.py in <module>
      2 from collections import namedtuple
      3 
----> 4 from velodyne_decoder.velodyne_decoder_pylib import *
      5 from velodyne_decoder.velodyne_decoder_pylib import __version__ as _pylib_version
      6 

ModuleNotFoundError: No module named 'velodyne_decoder.velodyne_decoder_pylib'`

**Comment by valgur** [comment]
Sorry about that. The `develop` branch is under active development and I accidentally introduced a regression when migrating the packaging setup to `scikit-build` and `conan`. It's fixed now.

**Comment by sparshtelus** [comment]
Thanks a lot
